<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $admin_module_record =[
             [
                'id' => 1,
                'parent_id' => 0,
                'name' => 'Transport Services',
                'module_name' => 'transport/service-list',
                'match_url' => 'transport/service-list',
                'route_path' => 'get:admin:transport_service_list',
                'route_path_arr' => '',
                'image' => 'fa-motorcycle',
                'module_action' => 1,
                'seq' => 2,
                'status' => 0,
                'is_access' => 1,
                 'module_category_type' => '1,5'
             ],
            [
                'id' => 2,
                'parent_id' => 0,
                'name' => 'Delivery Services',
                'module_name' => 'store/service-list',
                'match_url' => 'store/service-list',
                'route_path' => 'get:admin:store_service_list',
                'route_path_arr' => '',
                'image' => 'fa-store',
                'module_action' => 1,
                'seq' => 3,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => '2'
            ],
            [
                'id' => 3,
                'parent_id' => 0,
                'name' => 'Provider Services',
                'module_name' => 'other-services/service-list',
                'match_url' => 'provider-services/service-list',
                'route_path' => 'get:admin:other_service_list',
                'route_path_arr' => '',
                'image' => 'fad fa-users-cog',
                'module_action' => 1,
                'seq' => 4,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => '3,4'
            ],
            [
                'id' => 4,
                'parent_id' => 0,
                'name' => 'Coupon Deals',
                'module_name' => 'coupon-deals/service-list',
                'match_url' => 'coupon-deals/service-list',
                'route_path' => 'get:admin:coupon_deals_service_list',
                'route_path_arr' => '',
                'image' => 'fas fa-tags',
                'module_action' => 1,
                'seq' => 5,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => '6'
            ],
            [
                'id' => 5,
                'parent_id' => 0,
                'name' => 'Customers',
                'module_name' => 'customer-list',
                'match_url' => 'admin/customer-list',
                'route_path' => 'get:admin:user_list',
                'route_path_arr' => '',
                'image' => 'fas fa-users',
                'module_action' => 1,
                'seq' => 6,
                'status' => 1,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 6,
                'parent_id' => 0,
                'name' => 'Providers',
                'module_name' => '',
                'match_url' => '',
                'route_path' => 'get:admin:user_list',
                'route_path_arr' => '',
                'image' => 'fad fa-users-cog',
                'module_action' => 1,
                'seq' => 7,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 7,
                'parent_id' => 0,
                'name' => 'Incomplete Provider Registration',
                'module_name' => 'un-register-provider-list',
                'match_url' => 'admin/un-register-provider-list',
                'route_path' => 'get:admin:un_register_provider_list',
                'route_path_arr' => '',
                'image' => 'fa-user-alt-slash',
                'module_action' => 1,
                'seq' => 8,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 8,
                'parent_id' => 0,
                'name' => 'Push Notification',
                'module_name' => 'push-notification',
                'match_url' => 'admin/push-notification',
                'route_path' => 'get:admin:push_notification',
                'route_path_arr' => '',
                'image' => 'fa-bell',
                'module_action' => 1,
                'seq' => 10,
                'status' => 1,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 9,
                'parent_id' => 0,
                'name' => 'World Currency',
                'module_name' => 'world-currency-list',
                'match_url' => 'admin/world-currency-list',
                'route_path' => 'get:admin:world_currency_list',
                'route_path_arr' => '',
                'image' => 'fas fa-money-bill-wave',
                'module_action' => 1,
                'seq' => 11,
                'status' => 1,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 10,
                'parent_id' => 0,
                'name' => 'Site Settings',
                'module_name' => 'site-setting',
                'match_url' => 'admin/site-setting',
                'route_path' => 'get:admin:general_setting',
                'route_path_arr' => '',
                'image' => 'fas fa-users-cog',
                'module_action' => 1,
                'seq' => 12,
                'status' => 1,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 11,
                'parent_id' => 0,
                'name' => 'Page List',
                'module_name' => 'support-page-list',
                'match_url' => 'admin/support-page-list',
                'route_path' => 'get:admin:support_pages',
                'route_path_arr' => '',
                'image' => 'fas fa-clipboard-list',
                'module_action' => 1,
                'seq' => 13,
                'status' => 1,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 12,
                'parent_id' => 6,
                'name' => 'Delivery Person List',
                'module_name' => 'delivery-person-list',
                'match_url' => 'admin/delivery-person-list',
                'route_path' => 'get:admin:delivery_person_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 14,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 13,
                'parent_id' => 6,
                'name' => 'Transport Providers List',
                'module_name' => 'transprort-providers-list',
                'match_url' => 'transport/provider-list',
                'route_path' => 'get:admin:provider_list',
                'route_path_arr' => 'transport',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 15,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 14,
                'parent_id' => 6,
                'name' => 'Store Providers List',
                'module_name' => 'store-providers-list',
                'match_url' => 'store/provider-list',
                'route_path' => 'get:admin:provider_list',
                'route_path_arr' => 'store',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 16,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 15,
                'parent_id' => 6,
                'name' => 'Other Service Providers List',
                'module_name' => 'other-service-providers-list',
                'match_url' => 'provider-services/provider-list',
                'route_path' => 'get:admin:provider_list',
                'route_path_arr' => 'provider-services',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 17,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 16,
                'parent_id' => 6,
                'name' => 'Pending Provider List',
                'module_name' => 'pending-provider-list',
                'match_url' => 'admin/pending-provider-list',
                'route_path' => 'get:admin:pending_provider_list',
                'route_path_arr' => '',
                'image' => 'far fa-person-booth',
                'module_action' => 1,
                'seq' => 9,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 17,
                'parent_id' => 16,
                'name' => 'Delivery Person List',
                'module_name' => 'delivery-person-list',
                'match_url' => 'admin/delivery-person-list',
                'route_path' => 'get:admin:pending_delivery_person_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 18,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 18,
                'parent_id' => 16,
                'name' => 'Transport Providers List',
                'module_name' => 'transport-providers-list',
                'match_url' => 'transport/provider-list',
                'route_path' => 'get:admin:pending_transport_provider_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 19,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 19,
                'parent_id' => 16,
                'name' => 'Store Providers List',
                'module_name' => 'store-providers-list',
                'match_url' => 'store/provider-list',
                'route_path' => 'get:admin:pending_store_provider_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 20,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 20,
                'parent_id' => 16,
                'name' => 'Other Service Providers List',
                'module_name' => 'other-service-providers-list',
                'match_url' => 'provider-services/provider-list',
                'route_path' => 'get:admin:pending_other_provider_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 21,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 21,
                'parent_id' => 29,
                'name' => 'Home Page banner',
                'module_name' => 'home-page-banner-list',
                'match_url' => 'admin/home-page-banner-list',
                'route_path' => 'get:admin:home_page_banner_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 22,
                'status' => 0,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 22,
                'parent_id' => 0,
                'name' => 'Geo Fencing',
                'module_name' => 'restricted-area-list',
                'match_url' => 'restricted-area-list',
                'route_path' => 'get:admin:restricted_area_list',
                'route_path_arr' => '',
                'image' => 'fas fa-chart-area',
                'module_action' => 1,
                'seq' => 8,
                'status' => 1,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 23,
                'parent_id' => 0,
                'name' => 'Email Templates',
                'module_name' => 'email-templates',
                'match_url' => 'admin/email-templates',
                'route_path' => 'get:admin:email_templates',
                'route_path_arr' => '',
                'image' => 'fas fa-envelope-open-text',
                'module_action' => 1,
                'seq' => 23,
                'status' => 1,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 24,
                'parent_id' => 0,
                'name' => 'Language Lists',
                'module_name' => 'language-lists',
                'match_url' => 'admin/language-lists',
                'route_path' => 'get:admin:language_lists',
                'route_path_arr' => '',
                'image' => 'fas fa-language',
                'module_action' => 1,
                'seq' => 24,
                'status' => 0,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 25,
                'parent_id' => 0,
                'name' => 'Language Constant',
                'module_name' => 'language-constant',
                'match_url' => 'admin/language-constant',
                'route_path' => 'get:admin:language_constant',
                'route_path_arr' => '',
                'image' => 'fas fa-language',
                'module_action' => 1,
                'seq' => 25,
                'status' => 0,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 26,
                'parent_id' => 29,
                'name' => 'Home Page Slider',
                'module_name' => 'home-page-slider-list',
                'match_url' => 'admin/home-page-slider-list',
                'route_path' => 'get:admin:home_page_slider_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 22,
                'status' => 0,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 27,
                'parent_id' => 29,
                'name' => 'Home Page Feature Store',
                'module_name' => 'home-page-feature-store-list',
                'match_url' => 'admin/home-page-feature-store-list',
                'route_path' => 'get:admin:home_page_feature_store_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 28,
                'status' => 0,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 28,
                'parent_id' => 29,
                'name' => 'Ordering Service category',
                'module_name' => 'ordering-service-category-list',
                'match_url' => 'admin/ordering-service-category-list',
                'route_path' => 'get:admin:ordering_service_category_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 29,
                'status' => 0,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 29,
                'parent_id' => 0,
                'name' => 'App Home Page Setting',
                'module_name' => '',
                'match_url' => '',
                'route_path' => 'get:admin:home_page_banner_list',
                'route_path_arr' => '',
                'image' => 'fas fa-tools',
                'module_action' => 1,
                'seq' => 22,
                'status' => 0,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 30,
                'parent_id' => 29,
                'name' => 'Home Page Spot Light',
                'module_name' => 'home-page-sopt-light-list',
                'match_url' => 'admin/home-page-spot-light-list',
                'route_path' => 'get:admin:home_page_spot_light_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 31,
                'status' => 0,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 31,
                'parent_id' => 0,
                'name' => 'Drivers',
                'module_name' => 'drivers-list',
                'match_url' => 'admin/drivers-list/approved',
                'route_path' => '',
                'route_path_arr' => '',
                'image' => 'fa-motorcycle',
                'module_action' => 1,
                'seq' => 6,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 32,
                'parent_id' => 31,
                'name' => 'Add Driver',
                'module_name' => 'add-driver',
                'match_url' => 'admin/add-provider',
                'route_path' => 'get:admin:add_transport_service_driver',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 6,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 33,
                'parent_id' => 31,
                'name' => 'Approved Drivers',
                'module_name' => 'drivers-list',
                'match_url' => 'admin/drivers-list/approved',
                'route_path' => 'get:admin:transport_service_approved_providers_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 6,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 34,
                'parent_id' => 31,
                'name' => 'Un-Approved Drivers',
                'module_name' => 'drivers-list',
                'match_url' => 'admin/drivers-list/un-approved',
                'route_path' => 'get:admin:transport_service_un_approved_providers_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 6,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 35,
                'parent_id' => 31,
                'name' => 'Blocked Drivers',
                'module_name' => 'drivers-list',
                'match_url' => 'admin/drivers-list/blocked',
                'route_path' => 'get:admin:transport_service_blocked_providers_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 6,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 36,
                'parent_id' => 31,
                'name' => 'Reject Drivers',
                'module_name' => 'drivers-list',
                'match_url' => 'admin/drivers-list/rejected',
                'route_path' => 'get:admin:transport_service_rejected_providers_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 6,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 37,
                'parent_id' => 0,
                'name' => 'App Version Setting',
                'module_name' => 'app-version-setting',
                'match_url' => 'admin/app-version-setting',
                'route_path' => 'get:admin:app_version_setting',
                'route_path_arr' => '',
                'image' => 'fas fa-tools',
                'module_action' => 1,
                'seq' => 12,
                'status' => 1,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 38,
                'parent_id' => 0,
                'name' => 'City Area',
                'module_name' => 'city-area-list',
                'match_url' => 'city-area-list',
                'route_path' => 'get:admin:city_area_list',
                'route_path_arr' => '',
                'image' => 'fas fa-city',
                'module_action' => 1,
                'seq' => 8,
                'status' => 0,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 39,
                'parent_id' => 0,
                'name' => 'City Admin',
                'module_name' => 'city-admin-list',
                'match_url' => 'admin/city-admin-list',
                'route_path' => 'get:admin:city_admin_list',
                'route_path_arr' => '',
                'image' => 'fa-user-shield',
                'module_action' => 1,
                'seq' => 23,
                'status' => 0,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 40,
                'parent_id' => 29,
                'name' => 'Home Page Top Service',
                'module_name' => 'home-page-top-service-list',
                'match_url' => 'admin/home-page-top-service-list',
                'route_path' => 'get:admin:home_page_top_service_list',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => 1,
                'seq' => 22,
                'status' => 0,
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 41,
                'parent_id' => 0,
                'name' => 'Rides',
                'module_name' => 'Rides',
                'match_url' => '',
                'route_path' => '',
                'route_path_arr' => '',
                'image' => 'fa-taxi',
                'module_action' => 1,
                'seq' => 7,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 42,
                'parent_id' => 41,
                'name' => 'All Rides',
                'module_name' => 'Rides',
                'match_url' => 'admin/ride-list',
                'route_path' => 'get:admin:ride_list',
                'route_path_arr' => 'all',
                'image' => 'fa-taxi',
                'module_action' => 1,
                'seq' => 7,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 43,
                'parent_id' => 41,
                'name' => 'Pending Rides',
                'module_name' => 'Rides',
                'match_url' => 'admin/ride-list',
                'route_path' => 'get:admin:ride_list',
                'route_path_arr' => 'pending',
                'image' => 'fa-taxi',
                'module_action' => 1,
                'seq' => 7,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 44,
                'parent_id' => 41,
                'name' => 'Approved Rides',
                'module_name' => 'Rides',
                'match_url' => 'admin/ride-list',
                'route_path' => 'get:admin:ride_list',
                'route_path_arr' => 'approved',
                'image' => 'fa-taxi',
                'module_action' => 1,
                'seq' => 7,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 45,
                'parent_id' => 0,
                'name' => 'Service Settings',
                'module_name' => 'service settings',
                'match_url' => '',
                'route_path' => '',
                'route_path_arr' => '',
                'image' => 'fa-cog',
                'module_action' => 1,
                'seq' => 12,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 46,
                'parent_id' => 45,
                'name' => 'Settings',
                'module_name' => 'service settings',
                'match_url' => 'admin/service-setting',
                'route_path' => 'get:admin:service_setting',
                'route_path_arr' => '',
                'image' => 'fa-cog',
                'module_action' => 1,
                'seq' => 12,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 47,
                'parent_id' => 45,
                'name' => 'Promocode',
                'module_name' => 'service settings',
                'match_url' => 'admin/promocode-list',
                'route_path' => 'get:admin:promocode_list',
                'route_path_arr' => '',
                'image' => 'fa-cog',
                'module_action' => 1,
                'seq' => 12,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 48,
                'parent_id' => 45,
                'name' => 'Vehicle Type',
                'module_name' => 'service settings',
                'match_url' => 'admin/vehicle-type',
                'route_path' => 'get:admin:vehicle_type',
                'route_path_arr' => '',
                'image' => 'fa-cog',
                'module_action' => 1,
                'seq' => 12,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 49,
                'parent_id' => 45,
                'name' => 'Required Documents',
                'module_name' => 'service settings',
                'match_url' => 'admin/required-document-list',
                'route_path' => 'get:admin:required_document_list',
                'route_path_arr' => '',
                'image' => 'fa-cog',
                'module_action' => 1,
                'seq' => 12,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 50,
                'parent_id' => 0,
                'name' => 'Earning Report',
                'module_name' => 'Earning Report',
                'match_url' => 'admin/earning-report',
                'route_path' => 'get:admin:earning_report',
                'route_path_arr' => '',
                'image' => 'fa-money',
                'module_action' => 1,
                'seq' => 8,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 51,
                'parent_id' => 45,
                'name' => 'Vehicle Services',
                'module_name' => 'service settings',
                'match_url' => 'admin/vehicle-services',
                'route_path' => 'get:admin:vehicle_service',
                'route_path_arr' => '',
                'image' => 'fa-cog',
                'module_action' => 1,
                'seq' => 12,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 52,
                'parent_id' => 41,
                'name' => 'Scheduled Rides',
                'module_name' => 'Rides',
                'match_url' => 'admin/ride-list',
                'route_path' => 'get:admin:ride_list',
                'route_path_arr' => 'scheduled',
                'image' => 'fa-taxi',
                'module_action' => 1,
                'seq' => 7,
                'status' => 0,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 53,
                'parent_id' => 41,
                'name' => 'Ongoing Rides',
                'module_name' => 'Rides',
                'match_url' => 'admin/ride-list',
                'route_path' => 'get:admin:ride_list',
                'route_path_arr' => 'ongoing',
                'image' => 'fa-taxi',
                'module_action' => 1,
                'seq' => 7,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 54,
                'parent_id' => 41,
                'name' => 'Completed Rides',
                'module_name' => 'Rides',
                'match_url' => 'admin/ride-list',
                'route_path' => 'get:admin:ride_list',
                'route_path_arr' => 'completed',
                'image' => 'fa-taxi',
                'module_action' => 1,
                'seq' => 7,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 55,
                'parent_id' => 41,
                'name' => 'Cancelled Rides',
                'module_name' => 'Rides',
                'match_url' => 'admin/ride-list',
                'route_path' => 'get:admin:ride_list',
                'route_path_arr' => 'cancelled',
                'image' => 'fa-taxi',
                'module_action' => 1,
                'seq' => 7,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 56,
                'parent_id' => 0,
                'name' => 'Referral History',
                'module_name' => 'Referral',
                'match_url' => 'admin/referral-list',
                'route_path' => 'get:admin:referral_list',
                'route_path_arr' => 'cancelled',
                'image' => 'fa-certificate',
                'module_action' => 1,
                'seq' => 7,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 57,
                'parent_id' => 0,
                'name' => "God's View",
                'module_name' => 'gods view',
                'match_url' => 'admin/provider-location-on-map',
                'route_path' => 'get:admin:transport_provider_location',
                'route_path_arr' => 'cancelled',
                'image' => 'fa-street-view',
                'module_action' => 1,
                'seq' => 8,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
                //cash-out module
            [
                'id' => 58,
                'parent_id' => 0,
                'name' => "Cash Outs",
                'module_name' => '/cash-out',
                'match_url' => '/cash-out',
                'route_path' => 'get:admin:transport_cash_out_list',
                'route_path_arr' => '',
                'image' => 'fas fa-money-bill-wave',
                'module_action' => 1,
                'seq' => 8,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 59,
                'parent_id' => 0,
                'name' => 'SOS',
                'module_name' => 'manage',
                'match_url' => 'sos/manage',
                'route_path' => 'get:admin:sos',
                'route_path_arr' => 'sos',
                'image' => 'fa fa-phone',
                'module_action' => '1',
                'seq' => 8,
                'status' => '1',
                'is_access' => 0,
                'module_category_type' => null
            ],
            [
                'id' => 60,
                'parent_id' => 0,
                'name' => "Heat Map",
                'module_name' => 'heat map',
                'match_url' => 'admin/transport-heat-map',
                'route_path' => 'get:admin:transport_heat_map',
                'route_path_arr' => '',
                'image' => 'fa fa-map-pin',
                'module_action' => 1,
                'seq' => 8,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 61,
                'parent_id' => 0,
                'name' => "Search Radius",
                'module_name' => 'search radius',
                'match_url' => 'admin/search-radius',
                'route_path' => 'get:admin:search_radius_list',
                'route_path_arr' => '',
                'image' => 'fa fa-search',
                'module_action' => 1,
                'seq' => 13,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
            //Report Issue
            [
                'id' => 63,
                'parent_id' => 0,
                'name' => 'Report Issue',
                'module_name' => '',
                'match_url' => '',
                'route_path' => '',
                'route_path_arr' => '',
                'image' => 'fa-solid fa-file',
                'module_action' => '1',
                'seq' => 32,
                'status' => '1',
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 64,
                'parent_id' => 63,
                'name' => 'Customer Report Issues',
                'module_name' => 'customer-report-issues',
                'match_url' => 'admin/report-issue/customer',
                'route_path' => 'get:admin:report_issue',
                'route_path_arr' => 'customer',
                'image' => 'icon-home',
                'module_action' => '1',
                'seq' => 32,
                'status' => '1',
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 65,
                'parent_id' => 63,
                'name' => 'Driver Report Issues',
                'module_name' => 'driver-report-issues',
                'match_url' => 'admin/report-issue/driver',
                'route_path' => 'get:admin:report_issue',
                'route_path_arr' => 'driver',
                'image' => 'icon-home',
                'module_action' => '1',
                'seq' => 32,
                'status' => '1',
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 66,
                'parent_id' => 63,
                'name' => 'Report issue settings',
                'module_name' => 'report-issue-setting',
                'match_url' => 'admin/report-issue/setting',
                'route_path' => 'get:admin:report_issue_setting',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => '1',
                'seq' => 32,
                'status' => '1',
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 67,
                'parent_id' => 63,
                'name' => 'FAQs',
                'module_name' => 'FAQs',
                'match_url' => 'admin/report-issue/faqs/manage',
                'route_path' => 'get:admin:faqs',
                'route_path_arr' => '',
                'image' => 'icon-home',
                'module_action' => '1',
                'seq' => 32,
                'status' => '1',
                'is_access' => 1,
                'module_category_type' => null
            ],
            [
                'id' => 68,
                'parent_id' => 45,
                'name' => 'Comisiones por vehículo',
                'module_name' => 'service settings',
                'match_url' => 'admin/vehicle-commission-rates',
                'route_path' => 'get:admin:vehicle_commission_rates',
                'route_path_arr' => '',
                'image' => 'fa-percent',
                'module_action' => 1,
                'seq' => 12,
                'status' => 1,
                'is_access' => 1,
                'module_category_type' => null
            ],
        ];
        /*
        | upsert
        |--------------------------------------------------------------------------
        | We are using upsert here as it functions to either insert or update records efficiently.
        | If a record already exists, it updates it; if not, it inserts a new record.
        | This operation compares records using a unique key and supports handling multiple records in a single operation.
        */
        DB::table('admin_module')->upsert(
            $admin_module_record,
            ['id'], // Unique column to determine if a row exists
            ['parent_id','name', 'module_name', 'match_url', 'route_path', 'route_path_arr', 'image', 'module_action', 'seq', 'status', 'is_access', 'module_category_type']
        );
    }
}
