<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageConstatntSeeder extends Seeder
{
    public function run(): void
    {
        $language_constant_record =[
            [
                'id' => 1,
                'constant_name' => 'GET',
                'value' => 'Get',
                'pt_value' => 'Obter',
                'es_value' => 'Conseguir',
                'fr_value' => 'Obtenir',
                'it_value' => 'Ottenere',
            ],
            [
                'id' => 2,
                'constant_name' => 'OFF_ON_ALL_ORDERS',
                'value' => 'off on all orders',
                'pt_value' => 'Desligado em todos os pedidos',
                'es_value' => 'apagado en todos los pedidos',
                'fr_value' => 'réduction sur toutes les commandes',
                'it_value' => 'sconto su tutti gli ordini',
            ],
            [
                'id' => 3,
                'constant_name' => 'OFF_ON_ORDERS_ABOVE',
                'value' => 'off on orders above',
                'pt_value' => 'desconto em encomendas acima',
                'es_value' => 'descuento en pedidos superiores',
                'fr_value' => 'réduction sur les commandes au-dessus',
                'it_value' => 'sconto su ordini superiori',
            ],
            [
                'id' => 4,
                'constant_name' => 'RIDE_SERVICE',
                'value' => 'Ride Service',
                'pt_value' => 'Serviço de transporte',
                'es_value' => 'Servicio de viaje',
                'fr_value' => 'Service de transport',
                'it_value' => 'Servizio di trasporto',
            ],
            [
                'id' => 5,
                'constant_name' => 'COURIER_DELIVERY',
                'value' => 'Courier Delivery',
                'pt_value' => 'Entrega de correio',
                'es_value' => 'Entrega de mensajería',
                'fr_value' => 'Livraison par coursier',
                'it_value' => 'Consegna tramite corriere',
            ],
            [
                'id' => 6,
                'constant_name' => 'STORE_DELIVERY',
                'value' => 'Store Delivery',
                'pt_value' => 'Entrega na loja',
                'es_value' => 'Entrega en tienda',
                'fr_value' => 'Livraison en magasin',
                'it_value' => 'Consegna in negozio',
            ],
            [
                'id' => 7,
                'constant_name' => 'RENTAL_SERVICE',
                'value' => 'Rental Service',
                'pt_value' => 'Serviço de Aluguer',
                'es_value' => 'Servicio de alquiler',
                'fr_value' => 'Service de location',
                'it_value' => 'Servizio di noleggio',
            ],
            [
                'id' => 8,
                'constant_name' => 'SUN',
                'value' => 'Sun',
                'pt_value' => 'Sol',
                'es_value' => 'Sol',
                'fr_value' => 'Soleil',
                'it_value' => 'Dom',
            ],
            [
                'id' => 9,
                'constant_name' => 'MON',
                'value' => 'Mon',
                'pt_value' => 'Seg',
                'es_value' => 'Lun',
                'fr_value' => 'Lun',
                'it_value' => 'Lun',
            ],
            [
                'id' => 10,
                'constant_name' => 'TUE',
                'value' => 'Tue',
                'pt_value' => 'Ter',
                'es_value' => 'Mar',
                'fr_value' => 'Mar',
                'it_value' => 'Mar',
            ],
            [
                'id' => 11,
                'constant_name' => 'WED',
                'value' => 'Wed',
                'pt_value' => 'Qua',
                'es_value' => 'Mié',
                'fr_value' => 'Mer',
                'it_value' => 'Mer',
            ],
            [
                'id' => 12,
                'constant_name' => 'THU',
                'value' => 'Thu',
                'pt_value' => 'Qui',
                'es_value' => 'Jue',
                'fr_value' => 'Jeu',
                'it_value' => 'Gio',
            ],
            [
                'id' => 13,
                'constant_name' => 'FRI',
                'value' => 'Fri',
                'pt_value' => 'Sex',
                'es_value' => 'Vie',
                'fr_value' => 'Ven',
                'it_value' => 'Ven',
            ],
            [
                'id' => 14,
                'constant_name' => 'SAT',
                'value' => 'Sat',
                'pt_value' => 'Sáb',
                'es_value' => 'Sáb',
                'fr_value' => 'Sam',
                'it_value' => 'Sab',
            ],
            [
                'id' => 15,
                'constant_name' => 'FEATURED',
                'value' => 'Feature',
                'pt_value' => 'Característica',
                'es_value' => 'Característica',
                'fr_value' => 'Caractéristique',
                'it_value' => 'Caratteristica',
            ],
            [
                'id' => 16,
                'constant_name' => 'IN_SPOT_LIGHT',
                'value' => 'In Spot Light !',
                'pt_value' => 'Em destaque!',
                'es_value' => '¡En foco!',
                'fr_value' => 'En vedette !',
                'it_value' => 'In evidenza!',
            ],
            [
                'id' => 17,
                'constant_name' => 'FAVORITE',
                'value' => 'Favorite',
                'pt_value' => 'Favorita',
                'es_value' => 'Favorito',
                'fr_value' => 'Préféré',
                'it_value' => 'Preferito',
            ],
            [
                'id' => 18,
                'constant_name' => 'RECOMMENDED',
                'value' => 'Recommended',
                'pt_value' => 'Recomendada',
                'es_value' => 'Recomendado',
                'fr_value' => 'Recommandé',
                'it_value' => 'Consigliato',
            ],
            [
                'id' => 19,
                'constant_name' => 'TRANSPORT_SERVICES',
                'value' => 'Transport Services',
                'pt_value' => 'Serviços de transporte',
                'es_value' => 'Servicios de transporte',
                'fr_value' => 'Services de transport',
                'it_value' => 'Servizi di trasporto',
            ],
            [
                'id' => 20,
                'constant_name' => 'DELIVERY_SERVICES',
                'value' => 'Delivery Services',
                'pt_value' => 'Serviços de entrega',
                'es_value' => 'Servicios de entrega',
                'fr_value' => 'Services de livraison',
                'it_value' => 'Servizi di consegna',
            ],
            [
                'id' => 21,
                'constant_name' => 'PROVIDER_SERVICES',
                'value' => 'Provider Services',
                'pt_value' => 'Serviços do Provedor',
                'es_value' => 'Servicios del proveedor',
                'fr_value' => 'Services de prestataire',
                'it_value' => 'Servizi del fornitore',
            ],
        ];

        DB::table('language_constant')->upsert(
            $language_constant_record,
            ['id'],
            ['constant_name', 'value', 'pt_value', 'es_value', 'fr_value', 'it_value']
        );
    }
}
