[program:xisti-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/xisti-admin/artisan queue:work database --sleep=3 --tries=3 --timeout=120 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=ubuntu
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/xisti-admin/storage/logs/queue-worker.log
stopwaitsecs=3600
