<?php

return [
    'en' => [
        '1' => 'Credit by',
        '2' => 'Paid to On-demand - Order #',
        '3' => 'Paid to Store - Order #',
        '4' => 'Paid to Ride - #',
        '5' => 'Order refund from - Order #',
        '6' => 'Credit by admin',
        '7' => 'Paid for - Courier payment - Order #',
        '8' => 'Wallet amount transfer to ',
        '9' => 'Purchased coupons',
        '10' => 'Refund amount of Order #',
        '11' => 'Deposit from PayPal',
        '12' => 'Deposit from PayMongo',
        '13' => 'Debit by admin',
        '14' => 'Commission paid to XISTI - Booking #',
        '15' => 'Admin credited earnings - #',
        '16' => 'Admin debited commission - #',
        '17' => 'Debited by admin for your cashout request',
        '18' => 'Credited by admin as cashout request rejected',
        '19' => 'Account closed - wallet balance retained by XISTI',
    ],

    'es' => [
        '1' => 'Crédito por',
        '2' => 'Pagado a pedido - Pedido #',
        '3' => 'Pagado a la tienda - Pedido #',
        '4' => 'Pagado por viaje - #',
        '5' => 'Reembolso del pedido - Pedido #',
        '6' => 'Crédito por administrador',
        '7' => 'Pagado por - Pago de mensajería - Pedido #',
        '8' => 'Transferencia del saldo de la billetera a ',
        '9' => 'Cupones comprados',
        '10' => 'Monto de reembolso del pedido #',
        '11' => 'Depósito desde PayPal',
        '12' => 'Depósito desde PayMongo',
        '13' => 'Débito por administrador',
        '14' => 'Comisión pagada a XISTI - Reserva #',
        '15' => 'Ganancias acreditadas por el administrador - #',
        '16' => 'Comisión debitada por el administrador - #',
        '17' => 'Debitado por el administrador para su solicitud de retiro',
        '18' => 'Acreditado por el administrador por rechazo del retiro',
        '19' => 'Cuenta cerrada - saldo retenido por XISTI',
    ],

    'pt' => [
        '1' => 'Creditado por',
        '2' => 'Pago para On-demand - Pedido #',
        '3' => 'Pago para loja - Pedido #',
        '4' => 'Pago para viagem - #',
        '5' => 'Reembolso do pedido - Pedido #',
        '6' => 'Creditado pelo administrador',
        '7' => 'Pago por - Pagamento de entrega - Pedido #',
        '8' => 'Transferência do saldo da carteira para ',
        '9' => 'Cupons comprados',
        '10' => 'Valor do reembolso do pedido #',
        '11' => 'Depósito do PayPal',
        '12' => 'Depósito do PayMongo',
        '13' => 'Debitado pelo administrador',
        '14' => 'Comissão paga à XISTI - Reserva #',
        '15' => 'Ganhos creditados pelo administrador - #',
        '16' => 'Comissão debitada pelo administrador - #',
        '17' => 'Debitados pelo administrador para solicitação de saque',
        '18' => 'Creditados pelo administrador por rejeição do saque',
        '19' => 'Conta encerrada - saldo retido pela XISTI',
    ],

    'fr' => [
        '1' => 'Crédité par',
        '2' => 'Payé à la demande - Commande #',
        '3' => 'Payé au magasin - Commande #',
        '4' => 'Payé pour trajet - #',
        '5' => 'Remboursement de commande - Commande #',
        '6' => 'Crédité par admin',
        '7' => 'Payé pour - Paiement coursier - Commande #',
        '8' => 'Transfert du solde du portefeuille vers ',
        '9' => 'Coupons achetés',
        '10' => 'Montant du remboursement de la commande #',
        '11' => 'Dépôt depuis PayPal',
        '12' => 'Dépôt depuis PayMongo',
        '13' => 'Débité par admin',
        '14' => 'Commission payée à XISTI - Réservation #',
        '15' => 'Gains crédités par admin - #',
        '16' => 'Commission débitée par admin - #',
        '17' => 'Débité par admin pour votre demande de retrait',
        '18' => 'Crédité par admin suite au rejet du retrait',
        '19' => 'Compte fermé - solde conservé par XISTI',
    ],

    'it' => [
        '1' => 'Accreditato da',
        '2' => 'Pagato a richiesta - Ordine #',
        '3' => 'Pagato al negozio - Ordine #',
        '4' => 'Pagato per corsa - #',
        '5' => 'Rimborso ordine - Ordine #',
        '6' => 'Accreditato dall amministratore',
        '7' => 'Pagato per - Pagamento corriere - Ordine #',
        '8' => 'Trasferimento saldo portafoglio a ',
        '9' => 'Coupon acquistati',
        '10' => 'Importo rimborso ordine #',
        '11' => 'Deposito da PayPal',
        '12' => 'Deposito da PayMongo',
        '13' => 'Addebitato dall amministratore',
        '14' => 'Commissione pagata a XISTI - Prenotazione #',
        '15' => 'Guadagni accreditati dall amministratore - #',
        '16' => 'Commissione addebitata dall amministratore - #',
        '17' => 'Addebitato per richiesta di prelievo',
        '18' => 'Accreditato per rifiuto del prelievo',
        '19' => 'Account chiuso - saldo trattenuto da XISTI',
    ],
];
